### ISSUE TITLE
Running local registry

### ISSUE THREAD

**Issue by roboli** [PacktPublishing/A-Developer-s-Essential-Guide-to-Docker-Compose#2]
Hi. In chapter 04, when running the local registry example, I guess we need to run

```
docker compose -f registry.yaml up
```

in order to push the images to a local registry? That was the only way it worked for me.

**Comment by gkatzioura** [comment]
Hi @roboli. Indeed this the command to run first for the registry to take effect. Unfortunately it is omitted for the book, thus should be on the updated version. Thank you for you comment!
