### ISSUE TITLE
Chapter 3 typo error in docker-compose.yaml

### ISSUE THREAD

**Issue by vaambival** [PacktPublishing/A-Developer-s-Essential-Guide-to-Docker-Compose#5]
In Docker file network's name is 'task-manager-pubic-network'. I think it should be 'task-manager-pub**l**ic-network'

**Comment by gkatzioura** [comment]
Thank you for this. The typo is [resolved](https://github.com/PacktPublishing/A-Developer-s-Essential-Guide-to-Docker-Compose/commit/afbec27ceab6b6ea3e5ed778662232f04d751eab)
